# golangci-lint 設定ファイル
# Goコードの品質チェックツールの設定

# 実行設定
run:
  # タイムアウト設定（デフォルトは1分）
  timeout: 5m

  # 並列実行数（0 = CPU数に基づく自動設定）
  concurrency: 4

  # テストファイルもチェックする
  tests: true

  # ビルドタグ
  build-tags:
    - integration

# 出力設定
output:
  # 出力形式: colored-line-number, line-number, json, tab, checkstyle, code-climate
  format: colored-line-number

  # 結果を出力するかどうか
  print-issued-lines: true
  print-linter-name: true

# リンター設定
linters:
  # デフォルトで有効化するリンター
  enable:
    - errcheck      # エラーチェック漏れを検出
    - gosimple      # コードの簡略化を提案
    - govet         # 疑わしい構造を検出
    - ineffassign   # 無駄な代入を検出
    - staticcheck   # 静的解析
    - unused        # 未使用のコードを検出
    - gofmt         # フォーマットチェック
    - goimports     # import文のチェック
    - misspell      # スペルミスを検出
    - revive        # Goのコーディング規約チェック
    - gosec         # セキュリティ問題を検出
    - goconst       # 繰り返し文字列の定数化を提案
    - gocyclo       # 循環的複雑度をチェック
    - bodyclose     # HTTPレスポンスのbody.Close()漏れを検出
    - exportloopref # ループ変数のエクスポート問題を検出
    - sqlclosecheck # SQL関連のClose漏れを検出

  # 無効化するリンター（必要に応じてコメントアウト）
  disable:
    - typecheck  # 型チェック（go buildで検出されるため）

# リンターごとの設定
linters-settings:
  # errcheck: エラーチェック漏れの設定
  errcheck:
    # 無視する関数（例: fmt.Printfのエラーは通常無視）
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close

  # gocyclo: 循環的複雑度の閾値
  gocyclo:
    min-complexity: 15  # 15以上の複雑度で警告

  # goconst: 定数化の提案設定
  goconst:
    min-len: 3  # 最小文字数
    min-occurrences: 3  # 最小出現回数

  # misspell: スペルチェック設定
  misspell:
    locale: US  # 米国英語

  # revive: コーディング規約設定
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

  # gosec: セキュリティチェック設定
  gosec:
    excludes:
      - G404  # 弱い乱数生成器（開発環境では許容する場合）

# 問題の除外設定
issues:
  # 除外するファイルパターン
  exclude-rules:
    # テストファイルでは一部のチェックを緩和
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst

    # 自動生成されたファイルは除外
    - path: mock_.*\.go
      linters:
        - all

    # vendorディレクトリは除外
    - path: vendor/
      linters:
        - all

  # 最大表示する問題数（0 = 無制限）
  max-issues-per-linter: 0
  max-same-issues: 0

  # 新しい問題のみ報告する（既存コードの警告を無視）
  # new: true  # 必要に応じて有効化
